### ISSUE TITLE
Phase calbrate only on phase calibrators

### ISSUE THREAD

**Issue by jack-h** [COSMIC-SETI/active_observations#1]
It looks like COSMIC currently calibrates on any VLASS `CALIBRATE*` intent.

What different CALIBRATE intents has VLASS been seen to use? We should probably

1. Only calibrate COSMIC delay/phase from CALIBRATE_PHASE intents
2. Record uvh5 files for other (flux, polarization) calibrators, but not attempt to update COSMIC's delay/phase cals from them.

Has VLASS been using any calibrators which are not tagged with CALIBRATE_PHASE?

**Comment by jack-h** [comment]
grepping `/mnt/cosmic-storage-2/data0/logs/28Mar2023`

`grep ScanIntent:CALIBRATE observe_client.log | grep -v CALIBRATE_PHASE | grep CALIBRATE` I see `CALIBRATE_POL_LEAKAGE` `CALIBRATE_POL_ANGLE`, `CALIBRATE_FLUX`.

**Comment by Chenoachem** [comment]
Typically the "POL Leakage" and "Pol Angle" calibrators are not very bright in stokes I total intensity and can be extended. I would suggest we do not try to adjust phases on those sources.  Later, if we start looking at polarization data products, those will be important but for right now they could do more harm than good.

**Comment by Chenoachem** [comment]
Calibrate Flux would be good sources to save uvh5 files for even if we don't use.  But they are strong sources that could be used to calibrate phase.

**Comment by jack-h** [comment]
Is preferred behaviour to calibrate COSMIC on CALIBRATE_FLUX, or just store these for later (is there a possibility they are extended / otherwise inappropriate for phase calibration?)

**Comment by Chenoachem** [comment]
Either option. CALIBRATE_FLUX calibrators, in my experience, are still good for correct phases. But if it is easier to store one and use the other, that works too.  However, it is not uncommon to put the strong flux calibrator at the end of an observation run, which we would want to store, but wouldn't need to use as the observations would be complete.

**Comment by jack-h** [comment]
OK @talonmyburgh, for VLASS, let's do in-the-loop calibration on `CALIBRATE_PHASE` or `CALIBRATE_FLUX` (and store the resultant uvh5 files)
Don't calibrate on `CALIBRATE_POL*` but record the uvh5 files (cos why not?).

**Comment by talonmyburgh** [comment]
Sure thing. Will create a second observation `yaml` that mimics the calibration one but only records and moves the files to the storage node for `CALIBRATE_POL*`.

**Comment by jack-h** [comment]
Perfect, thanks. Can you please PR into this repo when it's in place so I
can vaguely keep track of what's going on?

**Comment by talonmyburgh** [comment]
Wont do anything yet @Chenoachem @jack-h as then we will miss the W51 `CALIBRATE_BANDPASS` intents... we would need to collude with @demorest to request that these "custom" observations use either of the calibration intents mentioned above...

**Comment by demorest** [comment]
I think CALIBRATE* should be fine.

**Comment by jack-h** [comment]
To be clear, this was never about all calibration runs (particularly TCOS which we control), just vlass. The potential issue was raised that polarization calibrators used by vlass would be weak and would cause cause COSMIC to generate poor solutions. @demorest is this not the case? Happy to close this issue as a NO-OP!

**Comment by demorest** [comment]
No the pol cal sources should be plenty bright.

**Comment by Chenoachem** [comment]
It has been my experience at least that not all pol calibrators are suitable for phase calibration. Some can be extended or be weak in Stokes I. Is that not true for the ones on the VLA or particularly with VLASS?

**Comment by demorest** [comment]
Polarization calibrators generally need to be even brighter than normal phase cal sources because polarization is at most ~10% of the total flux typically.  See https://science.nrao.edu/facilities/vla/docs/manuals/obsguide/modes/pol for more info.  Some of them are slightly resolved (for certain bands/configs) but I don't think they are large enough to cause big problems for us.

**Comment by jack-h** [comment]
Alrighty. Closing this with nothing to do!

**Comment by david-macmahon** [comment]
I'm a little late to the party, but can't flux calibrators be rather extended and therefore a poor choice for phase/delay calibration?

**Comment by jack-h** [comment]
That was one of the issues raised but I'm deferring completely to Paul.
